//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.05 at 09:31:48 AM CET 
//


package cursojava.spring.boot.servicios.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cursojava.spring.boot.servicios.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AltaCompra_QNAME = new QName("http://servicios.soap.cursojava/", "altaCompra");
    private final static QName _AltaCompraResponse_QNAME = new QName("http://servicios.soap.cursojava/", "altaCompraResponse");
    private final static QName _BuscarPorCodigo_QNAME = new QName("http://servicios.soap.cursojava/", "buscarPorCodigo");
    private final static QName _BuscarPorCodigoResponse_QNAME = new QName("http://servicios.soap.cursojava/", "buscarPorCodigoResponse");
    private final static QName _Echo_QNAME = new QName("http://servicios.soap.cursojava/", "echo");
    private final static QName _EchoResponse_QNAME = new QName("http://servicios.soap.cursojava/", "echoResponse");
    private final static QName _LasCompras_QNAME = new QName("http://servicios.soap.cursojava/", "lasCompras");
    private final static QName _LasComprasResponse_QNAME = new QName("http://servicios.soap.cursojava/", "lasComprasResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cursojava.spring.boot.servicios.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AltaCompra }
     * 
     */
    public AltaCompra createAltaCompra() {
        return new AltaCompra();
    }

    /**
     * Create an instance of {@link AltaCompraResponse }
     * 
     */
    public AltaCompraResponse createAltaCompraResponse() {
        return new AltaCompraResponse();
    }

    /**
     * Create an instance of {@link BuscarPorCodigo }
     * 
     */
    public BuscarPorCodigo createBuscarPorCodigo() {
        return new BuscarPorCodigo();
    }

    /**
     * Create an instance of {@link BuscarPorCodigoResponse }
     * 
     */
    public BuscarPorCodigoResponse createBuscarPorCodigoResponse() {
        return new BuscarPorCodigoResponse();
    }

    /**
     * Create an instance of {@link Echo }
     * 
     */
    public Echo createEcho() {
        return new Echo();
    }

    /**
     * Create an instance of {@link EchoResponse }
     * 
     */
    public EchoResponse createEchoResponse() {
        return new EchoResponse();
    }

    /**
     * Create an instance of {@link LasCompras }
     * 
     */
    public LasCompras createLasCompras() {
        return new LasCompras();
    }

    /**
     * Create an instance of {@link LasComprasResponse }
     * 
     */
    public LasComprasResponse createLasComprasResponse() {
        return new LasComprasResponse();
    }

    /**
     * Create an instance of {@link Compra }
     * 
     */
    public Compra createCompra() {
        return new Compra();
    }

    /**
     * Create an instance of {@link DatosCliente }
     * 
     */
    public DatosCliente createDatosCliente() {
        return new DatosCliente();
    }

    /**
     * Create an instance of {@link Entrada }
     * 
     */
    public Entrada createEntrada() {
        return new Entrada();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AltaCompra }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AltaCompra }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "altaCompra")
    public JAXBElement<AltaCompra> createAltaCompra(AltaCompra value) {
        return new JAXBElement<AltaCompra>(_AltaCompra_QNAME, AltaCompra.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AltaCompraResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AltaCompraResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "altaCompraResponse")
    public JAXBElement<AltaCompraResponse> createAltaCompraResponse(AltaCompraResponse value) {
        return new JAXBElement<AltaCompraResponse>(_AltaCompraResponse_QNAME, AltaCompraResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuscarPorCodigo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuscarPorCodigo }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "buscarPorCodigo")
    public JAXBElement<BuscarPorCodigo> createBuscarPorCodigo(BuscarPorCodigo value) {
        return new JAXBElement<BuscarPorCodigo>(_BuscarPorCodigo_QNAME, BuscarPorCodigo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BuscarPorCodigoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BuscarPorCodigoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "buscarPorCodigoResponse")
    public JAXBElement<BuscarPorCodigoResponse> createBuscarPorCodigoResponse(BuscarPorCodigoResponse value) {
        return new JAXBElement<BuscarPorCodigoResponse>(_BuscarPorCodigoResponse_QNAME, BuscarPorCodigoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Echo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Echo }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "echo")
    public JAXBElement<Echo> createEcho(Echo value) {
        return new JAXBElement<Echo>(_Echo_QNAME, Echo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EchoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EchoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "echoResponse")
    public JAXBElement<EchoResponse> createEchoResponse(EchoResponse value) {
        return new JAXBElement<EchoResponse>(_EchoResponse_QNAME, EchoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LasCompras }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LasCompras }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "lasCompras")
    public JAXBElement<LasCompras> createLasCompras(LasCompras value) {
        return new JAXBElement<LasCompras>(_LasCompras_QNAME, LasCompras.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LasComprasResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link LasComprasResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://servicios.soap.cursojava/", name = "lasComprasResponse")
    public JAXBElement<LasComprasResponse> createLasComprasResponse(LasComprasResponse value) {
        return new JAXBElement<LasComprasResponse>(_LasComprasResponse_QNAME, LasComprasResponse.class, null, value);
    }

}
